

export const ADDINGRIDENTS = 'ADDINGRIDENTS'
export const REMOVEINGRIDENTS = 'REMOVEINGRIDENTS'
export const SETINGREDIENTS = 'SETINGREDIENTS'
export const INGREDIENT_FETCHING_FAILED = 'INGREDIENT_FETCHING_FAILED'

export const PURCHASEBURGERSTART='PURCHASEBURGERSTART'
export const PURCHASEBURGERSUCCESS ='PURCHASEBURGERSUCCESS'
export const PURCHASEBURGERFAIL="PURCHASEBURGERFAIL"

export const RESETPURCHASESTATE ="RESETPURCHASESTATE"

export const FETCHORDERSTART ="FETCHORDERS"
export const FETCHORDERSUCCESS ="FETCHORDERSUCCESS"
export const FETCHORDERSFAIL ="FETCHORDERSFAIL"

export const AUTHSTART = "AUTHSTART"
export const AUTHSUCCESS = "AUTHSUCCESS"
export const AUTHFAIL = "AUTHFAIL"
export const AUTHLOGOUT="AUTHLOGOUT"



